### ISSUE TITLE
Issues while configuring virtual bridge

### ISSUE THREAD

**Issue by Cheesy008** [ghik/kubernetes-the-harder-way#13]
Hello. I'm trying to configure virtual bridge. By default my distro uses Network Manager. The `/etc/netplan` directory is empty. 
Firstly I tried to run commands via `ip`. After running `sudo ip addr add 192.168.1.1/24 dev kubr0` I got my Internet connection lost though kubr0 has appeared in `ip a`.
After PC reboot I tried to configure `netplan` configs. As I didn't have any default configs I put some for NetworkManager and bridges. I got the same problem with Internet connection. `kubr0` interface was created but I couldn't do any HTTP requests and it seems they all go in timeout.
I tried to do another bunch of different configurations using `nmcli`. As I understood the problem was that I was always try to add my physical eth0 device to the bridge but I don't understand how to do it properly.
In the end of the day I went with this config. I replaced `192.168.1.1/24` with `192.168.1.2/24`. 
```
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    enp6s0:
      dhcp4: true
  bridges:
    kubr0:
      addresses: [192.168.1.2/24]
```
I got my Internet connection working but after all manipulations with NAT and DHCP the VM has no access to Internet. There are some outputs from `ip route` and `ip a` in the VM
```
default via 192.168.1.2 dev enp0s2 proto dhcp src 192.168.1.10 metric 100 
192.168.1.0/24 dev enp0s2 proto kernel scope link src 192.168.1.10 metric 100 
192.168.1.2 dev enp0s2 proto dhcp scope link src 192.168.1.10 metric 100
```

```
2: enp0s2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:52:52:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.10/24 metric 100 brd 192.168.1.255 scope global dynamic enp0s2
       valid_lft 42040sec preferred_lft 42040sec
    inet6 fe80::5052:52ff:fe00:0/64 scope link 
       valid_lft forever preferred_lft forever
```
Would be very grateful to see your comment on this

**Comment by ghik** [comment]
The 192.168.1.0/24 or 192.168.0.0/16 prefix is most likely already used by your LAN and 192.168.1.1 is probably the IP of your router that gives you internet access. Try using something else for VMs, e.g. 192.168.42.0/24

**Comment by Cheesy008** [comment]
Thanks for response. I will try to use `192.168.42.1` for ip addresses and `192.168.42.0/24 ` for configuring iptables

**Comment by Cheesy008** [comment]
I couldn't resolve the problem after changing it to 192.168.42.0/24
ip a on vm gives me this output
```
default via 192.168.42.1 dev enp0s2 proto dhcp src 192.168.42.10 metric 100 
192.168.42.0/24 dev enp0s2 proto kernel scope link src 192.168.42.10 metric 100 
192.168.42.1 dev enp0s2 proto dhcp scope link src 192.168.42.10 metric 100
```
ip route
```
default via 192.168.42.1 dev enp0s2 proto dhcp src 192.168.42.10 metric 100 
192.168.42.0/24 dev enp0s2 proto kernel scope link src 192.168.42.10 metric 100 
192.168.42.1 dev enp0s2 proto dhcp scope link src 192.168.42.10 metric 100 
```
resolvectl status
```
Global
       Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
resolv.conf mode: stub

Link 2 (enp0s2)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=no/unsupported
Current DNS Server: 192.168.42.1
       DNS Servers: 192.168.42.1
        DNS Domain: kubenet
```

**Comment by ghik** [comment]
> ip a on vm gives me this output
Seems like you pasted the same output twice.

In general, it's hard to debug this without having full info about your environment. Make sure you have done everything from scratch. When trying to fix an issue retroactively, it's easy to forget about some steps. You can also try modifying and using the scripts provided by this repository - this way you'll reduce the chance of missing something.

**Comment by Cheesy008** [comment]
Fixed ip a output.
I've rechecked all of these configs starting from virtual bridge guide.
etc/dnsmasq.conf
```
interface=kubr0
bind-interfaces

dhcp-range=192.168.42.2,192.168.42.20,12h
dhcp-host=52:52:52:00:00:00,192.168.42.10
dhcp-host=52:52:52:00:00:01,192.168.42.11
dhcp-host=52:52:52:00:00:02,192.168.42.12
dhcp-host=52:52:52:00:00:03,192.168.42.13
dhcp-host=52:52:52:00:00:04,192.168.42.14
dhcp-host=52:52:52:00:00:05,192.168.42.15
dhcp-host=52:52:52:00:00:06,192.168.42.16
dhcp-authoritative

domain=kubenet
expand-hosts
```
etc/hosts
```
192.168.42.1   vmhost
192.168.42.10  gateway
192.168.42.11  control0
192.168.42.12  control1
192.168.42.13  control2
192.168.42.14  worker0
192.168.42.15  worker1
192.168.42.16  worker2
192.168.42.21  kubernetes
```
dnsmasq status after running the VM
```
● dnsmasq.service - DNSmasq DNS and DHCP server
     Loaded: loaded (/etc/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-05-27 21:37:18 +05; 33min ago
    Process: 29123 ExecStart=/etc/init.d/dnsmasq start (code=exited, status=0/SUCCESS)
   Main PID: 29134 (dnsmasq)
      Tasks: 1 (limit: 38239)
     Memory: 640.0K
        CPU: 97ms
     CGroup: /system.slice/dnsmasq.service
             └─29134 /usr/sbin/dnsmasq -x /run/dnsmasq/dnsmasq.pid -u dnsmasq -r /run/dnsmasq/resolv.conf -7 /etc/dnsmasq.d,.dpkg-dist,.dpkg-old,.dpkg-new --local-service --trust-anchor=.,20326,8,2,e06d44b80b8f1d39a95c0b0d7c65d08458e880409bbc683457104237c7f8ec8d

May 27 21:39:07 pop-os dnsmasq-dhcp[29134]: DHCPACK(kubr0) 192.168.42.10 52:52:52:00:00:00 gateway
May 27 21:55:25 pop-os dnsmasq-dhcp[29134]: DHCPDISCOVER(kubr0) 52:52:52:00:00:00
May 27 21:55:25 pop-os dnsmasq-dhcp[29134]: DHCPOFFER(kubr0) 192.168.42.10 52:52:52:00:00:00
May 27 21:55:25 pop-os dnsmasq-dhcp[29134]: DHCPREQUEST(kubr0) 192.168.42.10 52:52:52:00:00:00
May 27 21:55:25 pop-os dnsmasq-dhcp[29134]: abandoning lease to 52:52:52:00:00:00 of 192.168.42.10
May 27 21:55:25 pop-os dnsmasq-dhcp[29134]: DHCPACK(kubr0) 192.168.42.10 52:52:52:00:00:00 gateway
May 27 22:06:50 pop-os dnsmasq-dhcp[29134]: DHCPDISCOVER(kubr0) 52:52:52:00:00:00
May 27 22:06:50 pop-os dnsmasq-dhcp[29134]: DHCPOFFER(kubr0) 192.168.42.10 52:52:52:00:00:00
May 27 22:06:50 pop-os dnsmasq-dhcp[29134]: DHCPREQUEST(kubr0) 192.168.42.10 52:52:52:00:00:00
May 27 22:06:50 pop-os dnsmasq-dhcp[29134]: DHCPACK(kubr0) 192.168.42.10 52:52:52:00:00:00 gateway
```
After modifying iptables it appended `-A KUBENET_NAT -s 192.168.42.0/24 ! -o kubr0 -j MASQUERADE`

If these outputs seem ok to you then I think i have some misconfigurations with netplan

**Comment by ghik** [comment]
The guide assumes that `iptables` rules are initially empty on the host machine, thus allowing all traffic. If you already had some traffic blocked, then it is expected that you had to add more rules to allow the traffic to VMs.
