### ISSUE TITLE
Worker node certificates Script issues

### ISSUE THREAD

**Issue by wasifm** [ghik/kubernetes-the-harder-way#14]
The script to write out the control and worker car files has the "seq" starting at 1 instead of 0. This results in control0-csr.json not getting created.
Additionally the next step to generate the certificates has a syntax error in the for loop for vmnames array. It should be ${vmnames[@]}

**Comment by ghik** [comment]
Seems like I wrote these scripts for `zsh` and forgot to check them on `bash`. Thanks for reporting.
