### ISSUE TITLE
Permission error with vmnet-shared in QEMU when using custom network settings on macOS

### ISSUE THREAD

**Issue by hprabesh** [ghik/kubernetes-the-harder-way#16]
**Issue:**
When running `qemu-system-aarch64` on macOS with `vmnet-shared` and custom network settings (start-address, end-address, subnet-mask), a permission error occurs:

qemu-system-aarch64: -nic vmnet-shared,start-address=192.168.1.1,end-address=192.168.1.20,subnet-mask=255.255.255.0,mac=52:52:52:00:00:00: cannot create vmnet interface: general failure (possibly not enough privileges)

**Steps to reproduce:**
1. Run the following command:
   ```bash
   sudo qemu-system-aarch64 \
     -nographic \
     -machine virt \
     -nic vmnet-shared,start-address=192.168.1.1,end-address=192.168.1.20,subnet-mask=255.255.255.0 \
     -hda gateway/disk.img \
     -drive file=gateway/cidata.iso,driver=raw,if=virtio

macOS Version: 15.0
QEMU Version: QEMU emulator version 9.1.0

**Comment by hprabesh** [comment]
So, the problem was with the ip address range 192.168.1.1. For anyone facing the issue with newer version of MacOs, check out this GitHub issue: https://github.com/utmapp/UTM/issues/3294

I was able to resolve my issue by looking up the shared_address value in /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist and setting the start-address and end-address accordingly.

**Comment by ghik** [comment]
Yeah, it might be a good idea to use some other subnet in the guide overall. 192.168.1.0/24 is often taken by some already existing local network.

**Comment by JackWitherell** [comment]
For those who came across this info the same way as me, and encountered the same issues
10.0.0.X is typically a good prefix that you can use in lieu of 192.168.1.X
the following files will require swapping 192.168.1 for 10.0.0:

- -nic in the qemu launch command or in vmlaunch.sh
- lines 5 and 9 of restartdnsmasq
- /etc/hosts
- /opt/homebrew/etc/dnsmasq.conf

that should get you through that part of the tutorial. As you keep going you'll notice more instances where you need to swap out the ip, I'm listing a few more examples here:

- you'll need to customize the endpoints listed in the host section of kubernetes-csr.json and also in the script run to generate each worker and control csr

when setting up etcd
- you'll need to modify line 24 of the command to create the systemd file

when setting up Kubectl systemd as well
- lines 22 and 31 on the script to create systemd
