### ISSUE TITLE
Linux version: networking will not start on VM after rebooting the host

### ISSUE THREAD

**Issue by jftuga** [ghik/kubernetes-the-harder-way#5]
I twice followed this [section](https://github.com/ghik/kubernetes-the-harder-way/blob/linux/docs/02_Preparing_Environment_for_a_VM_Cluster.md) but was unable to get the networking running on the `gateway` VM after rebooting the host system.  Before a reboot, it works as expected.  When I did a console logon, I noticed the VM did not have the `192.168.1.10/24` IP address.

This is my fix, but I assume the guide needs to be updated somehow, but I am not sure what should be changed.

After I reboot the host VM and before booting the `gateway` VM, I run this script.  Afterwards, the VM gets its proper networking.  I am then able to ssh to it from the host, etc.

```bash
#!/usr/bin/env bash

sudo iptables -t nat -A POSTROUTING ! -o kubr0 -s 192.168.1.0/24 -j MASQUERADE
sudo systemctl daemon-reload
sudo systemctl enable kubenet-nat
sudo systemctl start kubenet-nat
sudo systemctl restart dnsmasq
```

All of these commands may not be necessary, but I didn't have time to narrow it down any further.

**Comment by ghik** [comment]
Hi, if you could try to reproduce this problem again, then pasted here the outputs `ip addr` and `sudo iptables-save` (just after reboot and without applying your fix), then we might have a better idea what's going on. It might be something specific to your setup.

**Comment by jftuga** [comment]
* `ip addr`

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever

2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 6c:2b:59:dd:ee:ff brd ff:ff:ff:ff:ff:ff
    altname enp0s31f6
    inet 172.14.15.179/24 brd 172.14.15.255 scope global dynamic noprefixroute eno1
       valid_lft 7104sec preferred_lft 7104sec
    inet6 fe80::4969:62a9:a11b:e54d/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever

3: kubr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether c2:21:65:39:79:7a brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.1/24 brd 192.168.1.255 scope global noprefixroute kubr0
       valid_lft forever preferred_lft forever
```

___

* `sudo iptables-save`

```
# Generated by iptables-save v1.8.7 on Sun Nov 19 09:30:39 2023
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:KUBENET_NAT - [0:0]
-A POSTROUTING -j KUBENET_NAT
-A KUBENET_NAT -s 192.168.1.0/24 ! -o kubr0 -j MASQUERADE
COMMIT
# Completed on Sun Nov 19 09:30:39 2023
```

**Comment by ghik** [comment]
That looks good. Maybe `dnsmasq` didn't start properly or is misconfigured?

**Comment by jftuga** [comment]
I have narrowed the problem down to just `dnsmasq`.

After a reboot, the only command that I need to run is:

`sudo systemctl restart dnsmasq`

and then the VM networking is running as expected.

___

Here is the contents of my `/etc/dnsmasq.conf`:

```ini
interface=kubr0
bind-interfaces
dhcp-range=192.168.1.2,192.168.1.20,12h
dhcp-host=52:52:52:00:00:00,192.168.1.10
dhcp-host=52:52:52:00:00:01,192.168.1.11
dhcp-host=52:52:52:00:00:02,192.168.1.12
dhcp-host=52:52:52:00:00:03,192.168.1.13
dhcp-host=52:52:52:00:00:04,192.168.1.14
dhcp-host=52:52:52:00:00:05,192.168.1.15
dhcp-host=52:52:52:00:00:06,192.168.1.16
dhcp-authoritative
domain=kubenet
expand-hosts
```

Do you see anything in the config that is incorrect?  Are there any other `dnsmasq` files that need to be reviewed?

**Comment by ghik** [comment]
It seems that at the moment of `dnsmasq` starting up, the network is not yet fully configured and `kubr0` interface does not exist. This is likely related to the fact that `dnsmasq` still uses the old style `/etc/init.d` scripts rather than `systemd`. I'll look into ways of fixing this.

**Comment by ghik** [comment]
I've included a [section](https://github.com/ghik/kubernetes-the-harder-way/blob/linux/docs/02_Preparing_Environment_for_a_VM_Cluster.md#making-sure-dnsmasq-starts-after-network) in the guide that explains how to fix this.

**Comment by jftuga** [comment]
Your fixed worked for me.  Thanks for spending time on this.  I'm closing this issue.
